services:
  db:
    image: postgres:16
    container_name: roomink-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: roomink
      POSTGRES_USER: roomink
      POSTGRES_PASSWORD: roomink
    ports:
      - "5433:5432"
    volumes:
      - roomink_db_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: roomink-mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1125:1025"

volumes:
  roomink_db_data: