# Generated by Django 4.2.28 on 2026-02-26 11:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avatar_url', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.PositiveIntegerField(help_text='分')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('display_name', models.CharField(blank=True, default='', max_length=50)),
                ('flag', models.CharField(choices=[('NONE', 'なし'), ('BAN', '出禁'), ('ATTENTION', '要注意')], default='NONE', max_length=12)),
                ('memo', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('REQUESTED', 'リクエスト'), ('CONFIRMED', '確定'), ('IN_PROGRESS', '施術中'), ('DONE', '完了'), ('CANCELLED', 'キャンセル')], default='REQUESTED', max_length=12)),
                ('memo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.cast')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.course')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timezone', models.CharField(default='Asia/Tokyo', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_phone', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('SENT', '送信済'), ('FAILED', '失敗')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.store')),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('store', 'name')},
            },
        ),
        migrations.CreateModel(
            name='OrderOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.option')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
            options={
                'unique_together': {('order', 'option')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='options',
            field=models.ManyToManyField(blank=True, through='core.OrderOption', to='core.option'),
        ),
        migrations.AddField(
            model_name='order',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.room'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.store'),
        ),
        migrations.AddField(
            model_name='option',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.store'),
        ),
        migrations.AddField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.store'),
        ),
        migrations.AddField(
            model_name='course',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.store'),
        ),
        migrations.CreateModel(
            name='CastAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cast_ack', to='core.order')),
            ],
        ),
        migrations.AddField(
            model_name='cast',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casts', to='core.store'),
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='core.cast')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='core.room')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='core.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'date'], name='core_shifta_store_i_ad545b_idx')],
                'unique_together': {('store', 'date', 'cast', 'start_time', 'end_time')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'cast', 'start'], name='core_order_store_i_23a581_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'room', 'start'], name='core_order_store_i_172514_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('store', 'phone')},
        ),
        migrations.AlterUniqueTogether(
            name='cast',
            unique_together={('store', 'name')},
        ),
    ]
