# Generated by Django 4.2.28 on 2026-02-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cti_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='calllog',
            name='core_calllo_store_i_6fdb1f_idx',
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['store', 'status', 'created_at'], name='core_calllo_store_i_2f90ca_idx'),
        ),
    ]
