# Generated by Django 4.2.28 on 2026-03-05 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cti_index_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('REQUESTED', '申請中'), ('APPROVED', '承認済'), ('REJECTED', '却下'), ('CANCELLED', '取消')], default='REQUESTED', max_length=12)),
                ('memo', models.TextField(blank=True, default='')),
                ('admin_memo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requests', to='core.cast')),
                ('desired_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_requests', to='core.room')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requests', to='core.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'date', 'status'], name='core_shiftr_store_i_6c5ab1_idx')],
            },
        ),
    ]
