# Generated by Django 4.2.28 on 2026-03-25 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_line_link_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('MORNING', '朝通知'), ('TWO_HOURS_BEFORE', '2時間前'), ('FIFTEEN_MIN_BEFORE', '15分前')], max_length=20)),
                ('status', models.CharField(choices=[('SENT', '送信済'), ('FAILED', '失敗'), ('SKIPPED', 'スキップ')], max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_notification_logs', to='core.cast')),
                ('shift_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_notification_logs', to='core.shiftassignment')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_notification_logs', to='core.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'shift_assignment', 'notification_type'], name='core_lineno_store_i_2af97b_idx')],
            },
        ),
    ]
