# Generated by Django 4.2.28 on 2026-04-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_store_line_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='年齢', null=True),
        ),
        migrations.AddField(
            model_name='cast',
            name='hp_url',
            field=models.URLField(blank=True, default='', help_text='HPのURL'),
        ),
        migrations.AddField(
            model_name='cast',
            name='introduction',
            field=models.TextField(blank=True, default='', help_text='店側紹介用コメント（お客様マイページ表示用）'),
        ),
        migrations.AddField(
            model_name='cast',
            name='staff_memo',
            field=models.TextField(blank=True, default='', help_text='運営専用メモ（manager/staffのみ閲覧可）'),
        ),
        migrations.AddField(
            model_name='course',
            name='target_casts',
            field=models.ManyToManyField(blank=True, help_text='表示対象キャスト（空なら全員に表示）', related_name='available_courses', to='core.cast'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ban_type',
            field=models.CharField(choices=[('NONE', 'なし'), ('STORE_BAN', '店出禁'), ('CAST_NG', '個別セラピNG')], default='NONE', help_text='出禁種別（flag=BAN 時に参照）', max_length=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='staff_memo',
            field=models.TextField(blank=True, default='', help_text='運営専用メモ（manager/staffのみ閲覧可）'),
        ),
    ]
