# Generated by Django 4.2.28 on 2026-04-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_phase1_customer_cast_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='course_back_rate',
            field=models.PositiveSmallIntegerField(default=0, help_text='コースバック率（%）'),
        ),
        migrations.AddField(
            model_name='cast',
            name='interval_minutes',
            field=models.PositiveSmallIntegerField(default=15, help_text='イ��ターバル時間（分）'),
        ),
        migrations.AddField(
            model_name='cast',
            name='option_fullback_enabled',
            field=models.BooleanField(default=False, help_text='オプション全額バック'),
        ),
    ]
