# Generated by Django 4.2.28 on 2026-04-03 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_phase2_cast_interval_backrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(help_text='名目（例: 雑費, 交通費, 備品代）', max_length=50)),
                ('amount', models.PositiveIntegerField(help_text='金額（円）')),
                ('per_order', models.BooleanField(default=False, help_text='True=予約件数×amount / False=日額amount')),
                ('memo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.cast')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_expenses', to='core.store')),
            ],
            options={
                'ordering': ['-date', 'cast', 'id'],
                'indexes': [models.Index(fields=['store', 'cast', 'date'], name='core_castex_store_i_1313ad_idx')],
            },
        ),
    ]
