# Generated by Django 4.2.28 on 2026-04-03 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_phase3_2_cast_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('points', models.IntegerField(help_text='正=加点 / 負=減点')),
                ('reason', models.CharField(blank=True, default='', max_length=100)),
                ('memo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_logs', to='core.cast')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_point_logs', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_logs', to='core.store')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['store', 'cast', 'date'], name='core_pointl_store_i_05a3c3_idx')],
            },
        ),
    ]
