# Generated by Django 4.2.28 on 2026-04-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_phase4_point_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('UNSET', '未設定'), ('CARD', 'カード'), ('CASH', '現金')], default='UNSET', max_length=10),
        ),
    ]
