# Generated by Django 4.2.28 on 2026-04-03 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_daily_settlement_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMergeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merged_customer_id', models.IntegerField(help_text='削除された顧客の元ID')),
                ('merged_customer_name', models.CharField(blank=True, default='', max_length=50)),
                ('merged_customer_phone', models.CharField(blank=True, default='', max_length=20)),
                ('orders_moved', models.PositiveIntegerField(default=0)),
                ('call_logs_moved', models.PositiveIntegerField(default=0)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_merges', to=settings.AUTH_USER_MODEL)),
                ('keep_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_logs_as_keep', to='core.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_logs', to='core.store')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
    ]
