# Generated by Django 4.2.28 on 2026-05-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_order_pending_finalize'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='clocked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
