# Generated by Django 4.2.28 on 2026-06-26 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0034_shiftrequest_approval_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastExpenseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='固定雑費名', max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('memo', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_templates', to='core.cast')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_expense_templates', to='core.store')),
            ],
            options={
                'ordering': ['cast', '-is_active', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CastExpenseTemplateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('memo', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField()),
                ('action', models.CharField(choices=[('CREATE', '新規作成'), ('UPDATE', '更新'), ('ACTIVATE', '有効化'), ('DEACTIVATE', '無効化')], max_length=10)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('cast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_template_history', to='core.cast')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cast_expense_template_edits', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='core.castexpensetemplate')),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
    ]
