# Generated by Django 4.2.28 on 2026-07-02 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0035_castexpensetemplate_castexpensetemplatehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastDailyCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('SUBMITTED', '提出済'), ('REVIEWED', '確認済'), ('RETURNED', '差戻し')], default='SUBMITTED', max_length=10)),
                ('done_count', models.PositiveIntegerField(default=0)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('estimated_pay', models.PositiveIntegerField(default=0)),
                ('course_sales', models.PositiveIntegerField(default=0)),
                ('options_sales', models.PositiveIntegerField(default=0)),
                ('actual_take_home_amount', models.PositiveIntegerField(default=0, help_text='実際の持ち帰り金額（キャスト入力）')),
                ('checklist_json', models.JSONField(blank=True, default=dict, help_text='退勤チェックリストの回答')),
                ('cast_memo', models.TextField(blank=True, default='')),
                ('manager_memo', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkouts', to='core.cast')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cast_checkout_reviews', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_daily_checkouts', to='core.store')),
            ],
            options={
                'ordering': ['-date', 'cast'],
            },
        ),
        migrations.CreateModel(
            name='CastCheckoutExpenseSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('memo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_snapshots', to='core.castdailycheckout')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_snapshots', to='core.castexpensetemplate')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='castdailycheckout',
            index=models.Index(fields=['store', 'date'], name='core_castda_store_i_479775_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='castdailycheckout',
            unique_together={('store', 'cast', 'date')},
        ),
    ]
