# Generated by Django 4.2.28 on 2026-07-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_castdailycheckout_castcheckoutexpensesnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='キャストによる出勤確認（事前）日時。Phase 3-B-1。clocked_in_at（実打刻）とは別概念。', null=True),
        ),
    ]
