# Generated by Django 4.2.28 on 2026-07-02 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0037_shiftassignment_confirmed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField(help_text='正=キャストへ追加で渡す金額 / 負=キャストから店へ戻す（差し引く）金額')),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField(blank=True, default='', help_text='マネージャーメモ（キャストにも表示される）')),
                ('status', models.CharField(choices=[('OPEN', '未解消'), ('RESOLVED', '解消済'), ('VOID', '無効')], default='OPEN', max_length=10)),
                ('source_type', models.CharField(choices=[('MANUAL', '手動'), ('CHECKOUT', '退勤提出'), ('ORDER', '予約'), ('OTHER', 'その他')], default='MANUAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_memo', models.TextField(blank=True, default='', help_text='解消・無効化時のメモ')),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='core.cast')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cast_adjustments', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_cast_adjustments', to=settings.AUTH_USER_MODEL)),
                ('source_checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='core.castdailycheckout')),
                ('source_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='core.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_adjustments', to='core.store')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['store', 'cast', 'date'], name='core_castad_store_i_02fea9_idx'), models.Index(fields=['store', 'status'], name='core_castad_store_i_c14774_idx')],
            },
        ),
    ]
