# Generated by Django 4.2.28 on 2026-07-03 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0038_castadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='castdailycheckout',
            name='net_sales_after_payment_fee',
            field=models.IntegerField(default=0, help_text='手数料差引後売上見込み（参考値）'),
        ),
        migrations.AddField(
            model_name='castdailycheckout',
            name='payment_fee_estimate',
            field=models.PositiveIntegerField(default=0, help_text='決済手数料見込み（参考値。給与確定・支払い処理には接続しない）'),
        ),
        migrations.AddField(
            model_name='room',
            name='area_name',
            field=models.CharField(blank=True, default='', help_text='エリアタグ（例: 新宿・池袋・渋谷・五反田）。空欄可＝未設定扱い。', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='card_fee_rate',
            field=models.PositiveSmallIntegerField(default=10, help_text='カード決済手数料率（%・参考値）'),
        ),
        migrations.AddField(
            model_name='store',
            name='cash_fee_rate',
            field=models.PositiveSmallIntegerField(default=0, help_text='現金決済手数料率（%・参考値）'),
        ),
        migrations.AddField(
            model_name='store',
            name='paypay_fee_rate',
            field=models.PositiveSmallIntegerField(default=5, help_text='PayPay決済手数料率（%・参考値）'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('UNSET', '未設定'), ('CARD', 'カード'), ('CASH', '現金'), ('PAYPAY', 'PayPay')], default='UNSET', max_length=10),
        ),
        migrations.CreateModel(
            name='ShiftConfirmNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(choices=[('TWO_HOURS', '2時間前'), ('ONE_HOUR', '1時間前')], max_length=10)),
                ('target_type', models.CharField(choices=[('CAST', 'キャスト'), ('MANAGER', 'マネージャー'), ('STAFF', 'スタッフ')], default='CAST', max_length=10)),
                ('channel', models.CharField(choices=[('NONE', '未設定（実送信なし）'), ('LINE', 'LINE'), ('SMS', 'SMS'), ('EMAIL', 'メール')], default='NONE', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', '送信予定'), ('SENT', '送信済'), ('SKIPPED', 'スキップ（テスト/実送信無効）'), ('FAILED', '失敗')], default='PENDING', max_length=10)),
                ('message', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_confirm_notification_logs', to='core.cast')),
                ('created_by', models.ForeignKey(blank=True, help_text='テストログを作成したユーザー（手動作成の場合）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_confirm_notification_logs', to=settings.AUTH_USER_MODEL)),
                ('shift_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_notification_logs', to='core.shiftassignment')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_confirm_notification_logs', to='core.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'shift_assignment', 'alert_level'], name='core_shiftc_store_i_48a9c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='CastNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, default='', help_text='カテゴリ（例: 施術マニュアル・接客メモ・店舗ルール・お知らせ）', max_length=50)),
                ('body', models.TextField(blank=True, default='', help_text='本文（プレーンテキストまたは簡易Markdown）')),
                ('status', models.CharField(choices=[('DRAFT', '下書き'), ('PUBLISHED', '公開'), ('ARCHIVED', 'アーカイブ')], default='DRAFT', max_length=10)),
                ('is_pinned', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('CAST', 'キャストのみ'), ('STAFF', 'スタッフのみ'), ('ALL', '全員')], default='CAST', max_length=10)),
                ('video_url', models.URLField(blank=True, default='', help_text='将来の動画掲載用URL（今回はアップロード等は未実装。任意入力欄のみ）')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cast_notes', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_notes', to='core.store')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cast_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
                'indexes': [models.Index(fields=['store', 'status', 'is_pinned'], name='core_castno_store_i_d386ce_idx')],
            },
        ),
    ]
