# Generated by Django 4.2.28 on 2026-07-15 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0039_castdailycheckout_net_sales_after_payment_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('RESERVATION_CONFIRMATION', '予約確認')], default='RESERVATION_CONFIRMATION', max_length=32)),
                ('payment_method', models.CharField(choices=[('UNSET', '未設定'), ('CARD', 'カード'), ('CASH', '現金'), ('PAYPAY', 'PayPay')], default='UNSET', max_length=10)),
                ('body', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=False, help_text='OFFの場合は既定文言を使用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='タイムライン（キャスト別表示）の並び順。0=未設定で既存順（名前順）。シフト時間・部屋には影響しない。'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sms_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smslog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='core.customer'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='smslog',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UNSET', '未設定'), ('CARD', 'カード'), ('CASH', '現金'), ('PAYPAY', 'PayPay')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='smslog',
            name='provider',
            field=models.CharField(choices=[('TWILIO', 'Twilio'), ('NONE', '未送信（ダミー）'), ('OTHER', 'その他')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='smslog',
            name='provider_message_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='smslog',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='core.store'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='template_type',
            field=models.CharField(choices=[('RESERVATION_CONFIRMATION', '予約確認'), ('RESERVATION_CANCELLED', '予約キャンセル'), ('CAST_NOTICE', 'キャスト通知'), ('REMINDER', 'リマインド'), ('OTHER', 'その他')], default='OTHER', max_length=32),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('PENDING', '送信中'), ('SENT', '送信済'), ('FAILED', '失敗'), ('SKIPPED', '対象外')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['order', '-sent_at'], name='core_smslog_order_i_daa1e7_idx'),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_templates', to='core.store'),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sms_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='smstemplate',
            unique_together={('store', 'template_type', 'payment_method')},
        ),
    ]
