# Generated by Django 5.2.16 on 2026-07-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0040_smstemplate_shiftassignment_display_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerAccountInvitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_customer_account_invitations", to=settings.AUTH_USER_MODEL)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="account_invitations", to="core.customer")),
                ("order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="customer_account_invitations", to="core.order")),
                ("sms_log", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="customer_account_invitations", to="core.smslog")),
            ],
        ),
        migrations.AlterField(
            model_name="smslog",
            name="status",
            field=models.CharField(choices=[("PENDING", "送信中"), ("SENT", "送信済"), ("FAILED", "失敗"), ("SKIPPED", "対象外"), ("DUMMY", "開発用ダミー"), ("CONFIG_MISSING", "設定不足")], max_length=20),
        ),
        migrations.AddIndex(
            model_name="customeraccountinvitation",
            index=models.Index(fields=["customer", "-created_at"], name="core_custom_custome_d56f1b_idx"),
        ),
    ]
