# Generated by Django 5.2.16 on 2026-08-09 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_order_extension_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CastUnavailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('type', models.CharField(choices=[('BREAK', '休憩'), ('LATE', '遅刻'), ('EARLY_LEAVE', '早退'), ('OUT', '中抜け'), ('STORE', '店舗都合'), ('OTHER', 'その他')], max_length=12)),
                ('memo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_times', to='core.cast')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cast_unavailable_times', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_unavailable_times', to='core.store')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cast_unavailable_times', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_at', 'id'],
                'indexes': [models.Index(fields=['store', 'cast', 'start_at'], name='core_castun_store_i_9e1aee_idx'), models.Index(fields=['store', 'start_at', 'end_at'], name='core_castun_store_i_121fe6_idx')],
            },
        ),
    ]
