# Generated by Django 5.2.17 on 2026-10-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_dailysettlementauditevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="castdailycheckout",
            name="customer_payment_surcharge",
            field=models.PositiveIntegerField(
                default=0,
                help_text="カード決済時に顧客へ上乗せした金額",
            ),
        ),
        migrations.AddField(
            model_name="castdailycheckout",
            name="customer_payment_total",
            field=models.PositiveIntegerField(
                default=0,
                help_text="顧客決済額合計（カード上乗せ分を含む）",
            ),
        ),
        migrations.AlterField(
            model_name="castdailycheckout",
            name="actual_take_home_amount",
            field=models.PositiveIntegerField(
                default=0,
                help_text="当日分の報酬として実際に持ち帰った現金（キャスト入力）",
            ),
        ),
        migrations.AlterField(
            model_name="castdailycheckout",
            name="payment_fee_estimate",
            field=models.PositiveIntegerField(
                default=0,
                help_text="店舗側決済手数料見込み（参考値。給与確定・支払い処理には接続しない）",
            ),
        ),
        migrations.AlterField(
            model_name="castdailycheckout",
            name="net_sales_after_payment_fee",
            field=models.IntegerField(
                default=0,
                help_text="顧客決済額から店舗側手数料を引いた売上見込み（参考値）",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="card_fee_rate",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="カード決済時の顧客上乗せ率（%）",
            ),
        ),
    ]
