# Generated by Django 5.2.17 on 2026-10-07 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_legacy_take_home_amount(apps, schema_editor):
    Checkout = apps.get_model('core', 'CastDailyCheckout')
    Checkout.objects.filter(room_cash_taken_amount=0).exclude(actual_take_home_amount=0).update(
        room_cash_taken_amount=models.F('actual_take_home_amount'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_castdailycheckout_customer_payment_totals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='castdailycheckout',
            name='cash_returned_to_room_amount',
            field=models.PositiveIntegerField(default=0, help_text='キャストがルームへ戻した現金（manager記録）'),
        ),
        migrations.AddField(
            model_name='castdailycheckout',
            name='office_cash_paid_amount',
            field=models.PositiveIntegerField(default=0, help_text='事務所からキャストへ別途渡した額（manager記録）'),
        ),
        migrations.AddField(
            model_name='castdailycheckout',
            name='room',
            field=models.ForeignKey(blank=True, help_text='当日の現金を管理する主なルーム', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_checkouts', to='core.room'),
        ),
        migrations.AddField(
            model_name='castdailycheckout',
            name='room_cash_taken_amount',
            field=models.PositiveIntegerField(default=0, help_text='ルーム内の現金からキャストが持ち帰った額'),
        ),
        migrations.AlterField(
            model_name='castdailycheckout',
            name='actual_take_home_amount',
            field=models.PositiveIntegerField(default=0, help_text='旧形式の持ち帰り金額（ルーム現金持ち帰り額と同期）'),
        ),
        migrations.RunPython(copy_legacy_take_home_amount, migrations.RunPython.noop),
        migrations.CreateModel(
            name='RoomCashCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('actual_cash_amount', models.PositiveIntegerField(default=0)),
                ('memo', models.TextField(blank=True, default='')),
                ('counted_at', models.DateTimeField(auto_now=True)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_cash_counts', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_counts', to='core.room')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_cash_counts', to='core.store')),
            ],
            options={
                'ordering': ['-date', 'room'],
                'unique_together': {('store', 'room', 'date')},
            },
        ),
    ]
