# Generated by Django 5.2.17 on 2026-10-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_receipts_for_existing_office_payments(apps, schema_editor):
    Checkout = apps.get_model('core', 'CastDailyCheckout')
    Receipt = apps.get_model('core', 'CastOfficeCashReceipt')
    for checkout in Checkout.objects.exclude(office_cash_paid_amount=0).iterator():
        Receipt.objects.create(
            store_id=checkout.store_id,
            cast_id=checkout.cast_id,
            checkout_id=checkout.id,
            amount=checkout.office_cash_paid_amount,
            received_on=checkout.date,
            memo='既存の事務所払い記録から移行',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_cast_cash_settlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CastOfficeCashReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('received_on', models.DateField()),
                ('memo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_cash_receipts', to='core.cast')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_cash_receipts', to='core.castdailycheckout')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_cast_office_cash_receipts', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_office_cash_receipts', to='core.store')),
            ],
            options={
                'ordering': ['-received_on', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='castofficecashreceipt',
            index=models.Index(fields=['store', 'cast', 'received_on'], name='core_castof_store_i_1bee1d_idx'),
        ),
        migrations.RunPython(create_receipts_for_existing_office_payments, migrations.RunPython.noop),
    ]
