# Generated by Django 5.2.17 on 2026-10-08 04:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_operator_memberships(apps, schema_editor):
    Profile = apps.get_model("core", "UserProfile")
    Membership = apps.get_model("core", "StoreMembership")
    db = schema_editor.connection.alias
    for profile in Profile.objects.using(db).filter(role__in=["staff", "manager"]).select_related("user").iterator():
        Membership.objects.using(db).get_or_create(
            user_id=profile.user_id, store_id=profile.store_id,
            defaults={"role": profile.role, "is_active": profile.user.is_active},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_system_announcements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreMembershipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('role', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_actions', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('staff', 'スタッフ'), ('manager', 'マネージャー')], max_length=10)),
                ('status', models.CharField(choices=[('pending', '承認待ち'), ('accepted', '承認済み'), ('declined', '辞退'), ('revoked', '取消済み')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_store_invitations', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_invitations', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.store')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('store', 'recipient'), name='unique_pending_store_invite'), models.CheckConstraint(condition=models.Q(('role__in', ['staff', 'manager'])), name='operator_invitation_role')],
            },
        ),
        migrations.CreateModel(
            name='StoreMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('staff', 'スタッフ'), ('manager', 'マネージャー')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'store'), name='unique_store_membership'), models.CheckConstraint(condition=models.Q(('role__in', ['staff', 'manager'])), name='operator_membership_role')],
            },
        ),
        migrations.RunPython(migrate_operator_memberships, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="userprofile", name="store",
            field=models.ForeignKey(to="core.store", on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, related_name="user_profiles"),
        ),
    ]
