# Generated by Django 5.2.17 on 2026-10-08 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_isolated_operation_groups(apps, schema_editor):
    """Give every existing store one private contract group without merging data."""
    Store = apps.get_model('core', 'Store')
    StoreMembership = apps.get_model('core', 'StoreMembership')
    OperationGroup = apps.get_model('core', 'OperationGroup')
    OperationGroupMembership = apps.get_model('core', 'OperationGroupMembership')
    OperationGroupEvent = apps.get_model('core', 'OperationGroupEvent')
    db = schema_editor.connection.alias

    for store in Store.objects.using(db).filter(operation_group__isnull=True).iterator():
        group = OperationGroup.objects.using(db).create(
            internal_label=f'契約グループ {store.pk}',
        )
        Store.objects.using(db).filter(pk=store.pk).update(operation_group_id=group.pk)
        OperationGroupEvent.objects.using(db).create(
            operation_group_id=group.pk,
            store_id=store.pk,
            action='legacy_group_created',
        )
        manager_ids = StoreMembership.objects.using(db).filter(
            store_id=store.pk,
            role='manager',
            is_active=True,
        ).values_list('user_id', flat=True)
        for user_id in manager_ids:
            membership, created = OperationGroupMembership.objects.using(db).get_or_create(
                operation_group_id=group.pk,
                user_id=user_id,
                defaults={'role': 'manager', 'is_active': True},
            )
            if created:
                OperationGroupEvent.objects.using(db).create(
                    operation_group_id=group.pk,
                    store_id=store.pk,
                    user_id=user_id,
                    action='legacy_manager_granted',
                )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_store_memberships_and_invitations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_label', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='operation_group',
            field=models.ForeignKey(blank=True, help_text='契約上の運営グループ。店舗利用者へ一覧表示しない。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='core.operationgroup'),
        ),
        migrations.CreateModel(
            name='OperationGroupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_group_actions', to=settings.AUTH_USER_MODEL)),
                ('operation_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.operationgroup')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_group_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperationGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', '運営管理者')], default='manager', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_memberships', to='core.operationgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('operation_group', 'user'), name='unique_operation_group_membership')],
            },
        ),
        migrations.RunPython(create_isolated_operation_groups, migrations.RunPython.noop),
    ]
