# Generated by Django 5.2.17 on 2026-10-08 15:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_operation_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_key', models.UUIDField(help_text='アプリインストール単位の公開識別子', unique=True)),
                ('kind', models.CharField(choices=[('personal', '個人端末'), ('shared', '共用端末')], max_length=12)),
                ('label', models.CharField(max_length=80)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('other', 'その他')], max_length=12)),
                ('status', models.CharField(choices=[('active', '受付中'), ('paused', '受付停止'), ('revoked', '失効済み')], db_index=True, default='active', max_length=12)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_work_devices', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkDeviceCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_prefix', models.CharField(blank=True, default='', max_length=12)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='core.workdevice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkDeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_device_actions', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.workdevice')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.store')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkDeviceLinkRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_key', models.UUIDField()),
                ('label', models.CharField(max_length=80)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('other', 'その他')], max_length=12)),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('claim_secret_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_work_device_links', to=settings.AUTH_USER_MODEL)),
                ('approved_stores', models.ManyToManyField(blank=True, related_name='work_device_link_requests', to='core.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device_key', '-created_at'], name='core_workde_device__2555da_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkDeviceStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_receiving', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_subscriptions', to='core.workdevice')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_device_subscriptions', to='core.store')),
            ],
            options={
                'ordering': ['store__name', 'store_id'],
                'constraints': [models.UniqueConstraint(fields=('device', 'store'), name='unique_work_device_store')],
            },
        ),
    ]
